import { prisma } from "../lib/prisma";

async function main() {
  console.log("Seeding database...");

  // Upsert the Admin user so this script can be run multiple times safely
  const adminEmail = "admin@sukisoftware.com";
  
  const admin = await prisma.user.upsert({
    where: { email: adminEmail },
    update: {},
    create: {
      email: adminEmail,
      name: "System Admin",
      // Note: In a real app, hash the password using bcrypt. 
      // For this seed, we will store a dummy hash or plain text just to have the record.
      // E.g., 'password123' hashed (you should replace this with a real hash generated by your auth logic)
      passwordHash: "$2b$10$Zmjb7QssYiqWTht6rr2.muxEoXcRdb8pz4gHL6sPzsYaTVASnM5LK", // bcrypt hash for 'password123'
      role: "Admin",
      isActive: true,
    },
  });

  console.log({ admin });
  console.log("Seeding finished.");
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
