export const INDUSTRY_TYPES = [
  "Automotive",
  "Pharma",
  "Textile",
  "FMCG",
  "Infrastructure",
  "Manufacturing",
  "Construction",
  "Real Estate",
  "IT / Software",
  "Electronics",
  "Chemicals",
  "Food & Beverage",
  "Healthcare",
  "Education",
  "Logistics",
  "Retail",
  "E-commerce",
  "Energy",
  "Telecom",
  "Agriculture",
  "Hospitality",
  "Others",
] as const;
